# Generated by Django 2.1.5 on 2019-02-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cns', models.CharField(max_length=18, unique=True, verbose_name='CNS')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('micro', models.PositiveIntegerField(verbose_name='Micro')),
                ('tipo', models.PositiveIntegerField(default=2, verbose_name='Tipo de Acesso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao Admin')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('update_on', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
            ],
            options={
                'verbose_name': 'ACS',
                'verbose_name_plural': 'ACS',
                'ordering': ['equipe__area', 'micro', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(verbose_name='Mês de Referência')),
                ('ano', models.PositiveIntegerField(default=2019, verbose_name='Ano de Referência')),
                ('dia', models.CharField(max_length=180, verbose_name='Dias')),
                ('vaga', models.PositiveIntegerField(verbose_name='Quantidade de Vagas por ACS')),
                ('tempo', models.PositiveIntegerField(default=20, verbose_name='Tempo Médio da Consulta')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['mes', 'ano'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('ine', models.CharField(max_length=10, verbose_name='INE')),
                ('area', models.PositiveIntegerField(verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('protese', models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], default=False, max_length=1, verbose_name='Usa prótese')),
                ('ativo', models.BooleanField(default=True, verbose_name='Consulta ativa:')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('update_on', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
            ],
            options={
                'verbose_name': 'Marcação',
                'verbose_name_plural': 'Marcações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=50, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
                'ordering': ['motivo'],
            },
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cns', models.CharField(max_length=18, unique=True, verbose_name='CNS')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('tipo', models.PositiveIntegerField(default=1, verbose_name='Tipo de Acesso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao Admin')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('update_on', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipe', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Odontólogo',
                'verbose_name_plural': 'Odontólogos',
                'ordering': ['equipe__area', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cnes', models.CharField(max_length=7, verbose_name='CNES')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cns', models.CharField(max_length=18, unique=True, verbose_name='CNS')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('tipo', models.PositiveIntegerField(default=3, verbose_name='Tipo de Acesso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao Admin')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('update_on', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
                ('acs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ACS', verbose_name='ACS')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='marcacao',
            name='motivo',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='core.Motivo', verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='marcacao',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipe', verbose_name='Equipe'),
        ),
        migrations.AddField(
            model_name='acs',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipe', verbose_name='Equipe'),
        ),
    ]
