# Generated by Django 2.0.4 on 2018-05-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cns', models.CharField(max_length=18, unique=True, verbose_name='CNS')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('update_on', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
            },
        ),
        migrations.CreateModel(
            name='ACS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('equipe', models.IntegerField(verbose_name='Equipe')),
                ('micro', models.IntegerField(verbose_name='Micro')),
            ],
            options={
                'verbose_name': 'ACS',
                'verbose_name_plural': 'ACS',
            },
        ),
        migrations.AddField(
            model_name='cadastro',
            name='acs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ACS', verbose_name='ACS'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
