# Generated by Django 2.0.4 on 2018-07-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acs',
            name='micro',
            field=models.PositiveIntegerField(default=1, verbose_name='Micro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marcacao',
            name='motivo',
            field=models.CharField(choices=[('1', 'Consulta de rotina'), ('2', 'Limpeza'), ('3', 'Tratamento clínico (Extração/Restauração)'), ('4', 'Prótese'), ('5', 'Outros motivos')], max_length=1, verbose_name='Motivo da consulta'),
        ),
    ]
