# Generated by Django 2.0.4 on 2018-06-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('1', 'Consulta de rotina'), ('2', 'Limpeza'), ('3', 'Tratamento Clínico (Extração/Restauração)'), ('4', 'Prótese'), ('5', 'Outros motivos')], max_length=1, verbose_name='Motivo da consulta')),
                ('protese', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Usa prótese')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('update_on', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cadastro', verbose_name='Usuário')),
            ],
        ),
    ]
