# Generated by Django 2.0.4 on 2018-06-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marcacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('ine', models.CharField(max_length=10, verbose_name='INE')),
                ('area', models.CharField(max_length=4, verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.AlterModelOptions(
            name='marcacao',
            options={'verbose_name': 'Cadastro', 'verbose_name_plural': 'Cadastros'},
        ),
        migrations.AlterField(
            model_name='acs',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipes', verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='marcacao',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Cadastro', verbose_name='Usuário'),
        ),
    ]
