# Generated by Django 2.0.4 on 2018-07-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180717_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacao',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario', verbose_name='Usuário'),
        ),
    ]
