# Generated by Django 2.0.4 on 2018-06-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180608_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipes', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Odontólogo',
                'verbose_name_plural': 'Odontólogos',
            },
        ),
    ]
