# Generated by Django 2.0.4 on 2018-08-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180718_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcacao',
            options={'ordering': ['data'], 'verbose_name': 'Marcação', 'verbose_name_plural': 'Marcações'},
        ),
        migrations.AlterModelOptions(
            name='motivo',
            options={'ordering': ['motivo'], 'verbose_name': 'Motivo', 'verbose_name_plural': 'Motivos'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
        migrations.AlterField(
            model_name='marcacao',
            name='motivo',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='core.Motivo', verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='marcacao',
            name='protese',
            field=models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], default=False, max_length=1, verbose_name='Usa prótese'),
        ),
    ]
