# Generated by Django 2.0.4 on 2018-06-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_odonto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acs',
            options={'ordering': ['equipe', 'micro', 'nome'], 'verbose_name': 'ACS', 'verbose_name_plural': 'ACS'},
        ),
        migrations.AlterModelOptions(
            name='marcacao',
            options={'verbose_name': 'Marcação', 'verbose_name_plural': 'Marcações'},
        ),
        migrations.AddField(
            model_name='cadastro',
            name='is_odonto',
            field=models.BooleanField(default=False, verbose_name='Odontólogo'),
        ),
        migrations.AlterField(
            model_name='odonto',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cadastro', verbose_name='Nome'),
        ),
    ]
