# Generated by Django 2.0.4 on 2018-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180608_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacao',
            name='data',
            field=models.DateField(default='2018-01-01', verbose_name='Data'),
        ),
    ]
