# Generated by Django 2.0.4 on 2018-08-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180810_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cnes', models.CharField(max_length=7, verbose_name='INE')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Unidade', verbose_name='Unidade'),
            preserve_default=False,
        ),
    ]
