# Generated by Django 2.0.4 on 2018-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_marcacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacao',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
