# Generated by Django 2.0.4 on 2018-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180816_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=2, verbose_name='Mês de Referência')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano de Referência')),
                ('dia', models.CharField(max_length=2, verbose_name='Dias da Semana')),
                ('tempo', models.CharField(choices=[((0, 1, 2, 3, 4, 5, 6), 'segunda'), ((0, 1, 2, 3, 4, 5, 6), 'terça'), ((0, 1, 2, 3, 4, 5, 6), 'quarta'), ((0, 1, 2, 3, 4, 5, 6), 'quinta'), ((0, 1, 2, 3, 4, 5, 6), 'sexta'), ((0, 1, 2, 3, 4, 5, 6), 'sábado'), ((0, 1, 2, 3, 4, 5, 6), 'domingo')], max_length=2, verbose_name='Tempo Médio da Consulta')),
            ],
        ),
        migrations.AlterModelOptions(
            name='acs',
            options={'ordering': ['equipe__area', 'micro', 'nome'], 'verbose_name': 'ACS', 'verbose_name_plural': 'ACS'},
        ),
        migrations.AlterModelOptions(
            name='equipe',
            options={'ordering': ['area'], 'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
        migrations.AlterModelOptions(
            name='marcacao',
            options={'ordering': ['-data'], 'verbose_name': 'Marcação', 'verbose_name_plural': 'Marcações'},
        ),
        migrations.AlterModelOptions(
            name='odontologo',
            options={'ordering': ['equipe__area', 'nome'], 'verbose_name': 'Odontólogo', 'verbose_name_plural': 'Odontólogos'},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['nome'], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cnes',
            field=models.CharField(max_length=7, verbose_name='CNES'),
        ),
    ]
