# Generated by Django 2.0.4 on 2018-07-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180704_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipes',
            name='area',
            field=models.IntegerField(verbose_name='Área'),
        ),
    ]
