# Generated by Django 2.0.4 on 2018-08-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180816_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='acs',
            name='tipo',
            field=models.PositiveIntegerField(default=2, verbose_name='Tipo de Acesso'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='tipo',
            field=models.PositiveIntegerField(default=1, verbose_name='Tipo de Acesso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.PositiveIntegerField(default=3, verbose_name='Tipo de Acesso'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='ano',
            field=models.CharField(default=2018, max_length=4, verbose_name='Ano de Referência'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.CharField(choices=[((0, 1, 2, 3, 4, 5, 6), 'Segunda'), ((0, 1, 2, 3, 4, 5, 6), 'Terça'), ((0, 1, 2, 3, 4, 5, 6), 'Quarta'), ((0, 1, 2, 3, 4, 5, 6), 'Quinta'), ((0, 1, 2, 3, 4, 5, 6), 'Sexta'), ((0, 1, 2, 3, 4, 5, 6), 'Sábado'), ((0, 1, 2, 3, 4, 5, 6), 'Domingo')], max_length=2, verbose_name='Dias da Semana'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='mes',
            field=models.CharField(default='09', max_length=2, verbose_name='Mês de Referência'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tempo',
            field=models.PositiveIntegerField(default=20, verbose_name='Tempo Médio da Consulta'),
        ),
    ]
