# Generated by Django 2.0.4 on 2018-08-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180816_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.CharField(choices=[((0, 1, 2, 3, 4, 5, 6), 'Segunda'), ((0, 1, 2, 3, 4, 5, 6), 'Terça'), ((0, 1, 2, 3, 4, 5, 6), 'Quarta'), ((0, 1, 2, 3, 4, 5, 6), 'Quinta'), ((0, 1, 2, 3, 4, 5, 6), 'Sexta'), ((0, 1, 2, 3, 4, 5, 6), 'Sábado'), ((0, 1, 2, 3, 4, 5, 6), 'Domingo')], max_length=2, verbose_name='Dias da Semana'),
        ),
    ]
