# Generated by Django 2.0.4 on 2018-08-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180816_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='acs',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Acesso Admin'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Acesso Admin'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Acesso Admin'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.CharField(choices=[((0, 1, 2, 3, 4, 5, 6), 'Segunda'), ((0, 1, 2, 3, 4, 5, 6), 'Terça'), ((0, 1, 2, 3, 4, 5, 6), 'Quarta'), ((0, 1, 2, 3, 4, 5, 6), 'Quinta'), ((0, 1, 2, 3, 4, 5, 6), 'Sexta'), ((0, 1, 2, 3, 4, 5, 6), 'Sábado'), ((0, 1, 2, 3, 4, 5, 6), 'Domingo')], max_length=2, verbose_name='Dias da Semana'),
        ),
    ]
