# Generated by Django 2.0.4 on 2018-08-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180817_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='vaga',
            field=models.PositiveIntegerField(default=10, verbose_name='Quantidade de Vagas por ACS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.CharField(choices=[((0, 1, 2, 3, 4, 5, 6), 'Segunda'), ((0, 1, 2, 3, 4, 5, 6), 'Terça'), ((0, 1, 2, 3, 4, 5, 6), 'Quarta'), ((0, 1, 2, 3, 4, 5, 6), 'Quinta'), ((0, 1, 2, 3, 4, 5, 6), 'Sexta'), ((0, 1, 2, 3, 4, 5, 6), 'Sábado'), ((0, 1, 2, 3, 4, 5, 6), 'Domingo')], max_length=2, verbose_name='Dias da Semana'),
        ),
    ]
