# Generated by Django 2.0.4 on 2018-08-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180817_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='equipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Equipe', verbose_name='Equipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.CharField(choices=[((0, 1, 2, 3, 4, 5, 6), 'Segunda'), ((0, 1, 2, 3, 4, 5, 6), 'Terça'), ((0, 1, 2, 3, 4, 5, 6), 'Quarta'), ((0, 1, 2, 3, 4, 5, 6), 'Quinta'), ((0, 1, 2, 3, 4, 5, 6), 'Sexta'), ((0, 1, 2, 3, 4, 5, 6), 'Sábado'), ((0, 1, 2, 3, 4, 5, 6), 'Domingo')], default=False, max_length=2, verbose_name='Dias da Semana'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='mes',
            field=models.CharField(choices=[((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), ''), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Janeiro'), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Fevereiro'), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Março'), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Abril'), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Maio'), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Junho'), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Julho'), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Agosto'), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Setembro'), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Outubro'), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Novembro'), ((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 'Dezembro')], default=False, max_length=2, verbose_name='Mês de Referência'),
        ),
    ]
