# Generated by Django 2.0.4 on 2018-08-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180817_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='ano',
            field=models.PositiveIntegerField(default=2018, verbose_name='Ano de Referência'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.PositiveIntegerField(verbose_name='Dias da Semana'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='mes',
            field=models.PositiveIntegerField(verbose_name='Mês de Referência'),
        ),
    ]
