# Generated by Django 2.0.4 on 2018-08-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180820_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.CharField(max_length=35, verbose_name='Dias da Semana'),
        ),
    ]
