# Generated by Django 2.0.4 on 2018-09-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180820_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['mes', 'ano'], 'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
    ]
