# Generated by Django 2.0.4 on 2018-09-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180906_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.CharField(max_length=180, verbose_name='Dias'),
        ),
    ]
