# Generated by Django 2.0.4 on 2018-09-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180913_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_locked',
        ),
    ]
