# Generated by Django 2.0.4 on 2018-09-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_usuario_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
    ]
